### ISSUE TITLE
GPU version on the way？

### ISSUE THREAD

**Issue by julinfn** [dinglufe/segment-anything-cpp-wrapper#1]

**Comment by dinglufe** [comment]
Yes, I am still working on it.

**Comment by dinglufe** [comment]
[Release 1.3](https://github.com/dinglufe/segment-anything-cpp-wrapper/releases/tag/v1.3) now supports execution using CUDA.

**Comment by bnascimento** [comment]
do we need to re-export the onnx models to CUDA? how?

**Comment by dinglufe** [comment]
No need to re-export. But using CUDA did not provide a significant improvement in efficiency (only about 4 times faster on my computer).
