### ISSUE TITLE
Add Sam-HQ support?

### ISSUE THREAD

**Issue by twardoch** [dinglufe/segment-anything-cpp-wrapper#13]
MobileSAM & FastSAM are "fast", but there is also another direction: https://github.com/SysCV/sam-hq — it would be wonderful if you could add support for it as well :)

**Comment by dinglufe** [comment]
Thank you! I'll give it a try to add support for HQ-SAM.

**Comment by dinglufe** [comment]
HQ-SAM is now supported in [v1.5](https://github.com/dinglufe/segment-anything-cpp-wrapper/releases/tag/v1.5)
