### ISSUE TITLE
bash ./vcpkg install opencv:x64-windows gflags:x64-windows onnxruntime-gpu:x64-windows An error occurred mounting one of your file systems. Please run 'dmesg' for more details.

### ISSUE THREAD

**Issue by lixinye666** [dinglufe/segment-anything-cpp-wrapper#15]
bash ./vcpkg install opencv:x64-windows gflags:x64-windows onnxruntime-gpu:x64-windows
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.

你好，请问您了解这是因为啥吗

**Comment by dinglufe** [comment]
What system and compiler are you using? Currently, I have only tested it on the combination of Windows 10 + VS2019 and Ubuntu 18.04 + gcc7. Additionally, any issues related to vcpkg may be raised in the official community, for example, at https://github.com/microsoft/vcpkg.

**Comment by lixinye666** [comment]
我直接在cmd运行的./vcpkg install opencv:x64-windows gflags:x64-windows onnxruntime-gpu:x64-windows
