### ISSUE TITLE
调用报错

### ISSUE THREAD

**Issue by kc-w** [dinglufe/segment-anything-cpp-wrapper#19]
调用option.AppendExecutionProvider_CUDA(options);函数报错
![image](https://github.com/dinglufe/segment-anything-cpp-wrapper/assets/39193398/d2472d54-a395-4437-9463-eac83e01aa1b)

使用的onnx版本为onnxruntime-win-x64-gpu-1.15.1

**Comment by dinglufe** [comment]
It could be due to the CUDA-related DLL files not being in the same folder as the exe file or not included in the PATH environment variable. You can refer to the files in the compressed package in releases page.
