### ISSUE TITLE
Can you show all the test project code.I cann't run in my compute after I create a new project and and test.cpp into project.

### ISSUE THREAD

**Issue by yjl617** [dinglufe/segment-anything-cpp-wrapper#28]
Can you show all the test project code.I cann't run in my compute after I create a new project and and test.cpp into project.

**Comment by dinglufe** [comment]
The code in the repository is complete. You can refer to the project file [CMakeLists.txt](https://github.com/dinglufe/segment-anything-cpp-wrapper/blob/main/CMakeLists.txt) for compilation.
