### ISSUE TITLE
Is there a way to generator mask for the entire image?

### ISSUE THREAD

**Issue by jason-chen-site** [dinglufe/segment-anything-cpp-wrapper#3]

**Comment by dinglufe** [comment]
I implemented a simplified version based on the [official demo](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/automatic_mask_generator_example.ipynb). 

See this [commit](https://github.com/dinglufe/segment-anything-cpp-wrapper/commit/b3a28a04173a2571c0ff07818b05d6b17b04bf97) and [release v1.1](https://github.com/dinglufe/segment-anything-cpp-wrapper/releases/tag/v1.1).

Screenshot:

![sam-auto-segmentation](https://github.com/dinglufe/segment-anything-cpp-wrapper/assets/7950636/c560087d-75a1-4b9e-b716-4c23bed604d1)
