### ISSUE TITLE
help!!! I use it as this,but get error:not enough space: expected 4194304, got 0. My memory is enough.What's wrong?

### ISSUE THREAD

**Issue by yjl617** [dinglufe/segment-anything-cpp-wrapper#31]
help!!! I use it as this,but get error:not enough space: expected 4194304, got 0. My memory is enough.What's wrong?
thresholdMat = sam.getMask({500,400});

**Comment by dinglufe** [comment]
Can reducing the parameters solve this issue? For example, (50, 40).

**Comment by yjl617** [comment]
Thank you for your reply. I have resolve this problem. I think maby is some version not right.

**Comment by klein0809** [comment]
> help!!! I use it as this,but get error:not enough space: expected 4194304, got 0. My memory is enough.What's wrong? thresholdMat = sam.getMask({500,400});

Hello, I have the same issue. How do you solve it? Appreciate!
