### ISSUE TITLE
How to change the image size, still only 1024x720?

### ISSUE THREAD

**Issue by yjl617** [dinglufe/segment-anything-cpp-wrapper#33]
How to change the image size, still only 1024x720?I see that the recognition result is still different from the demo on the official website, I wonder if it's because of this reason?

**Comment by dinglufe** [comment]
Dynamic loading of size still hasn't been implemented. But by modifying the [preprocessing script](https://github.com/dinglufe/segment-anything-cpp-wrapper/blob/090f350af7f2234add0705b9214fcf1376ccf629/export_pre_model.py#L32) and exporting, other sizes (not exceeding 1024x1024) can be used.

**Comment by yjl617** [comment]
ok,  Thank you very much!
