### ISSUE TITLE
Why I don't get as good results as you do in the python environment, I'm curious to know how you did it and what tips you have.

### ISSUE THREAD

**Issue by Dkwda** [dinglufe/segment-anything-cpp-wrapper#35]
@dinglufe

**Comment by Dkwda** [comment]
As far as I know, the original SAM will output 4 masks, do you choose an optimal mask for output

**Comment by dinglufe** [comment]
Have you tried the official demo? It generated similar results to the Python code in my test. 

Comparisons:
1. [HQ-SAM](https://github.com/SysCV/sam-hq#visual-comparison-between-sam-and-hq-sam): 
https://github.com/SysCV/sam-hq#visual-comparison-between-sam-and-hq-sam
2. This repo:
https://github.com/dinglufe/segment-anything-cpp-wrapper/releases/tag/v1.5
