### ISSUE TITLE
opencv2/opencv.hpp: No such file or directory

### ISSUE THREAD

**Issue by Mareeta26** [dinglufe/segment-anything-cpp-wrapper#39]
I was trying to run the program in VsCode and followed the steps as specified.  I have installed vcpkg and the opencv folders are already in it.
But, when I run test.cpp, the following error is shown
**"opencv2/opencv.hpp: No such file or directory".**

Can you please advise how to solve?
Thank you,
Mareeta

**Comment by dinglufe** [comment]
Has OpenCV been installed in vcpkg?

`./vcpkg install opencv:x64-windows gflags:x64-windows onnxruntime-gpu:x64-windows`
