### ISSUE TITLE
Support EdgeSam

### ISSUE THREAD

**Issue by sctrueew** [dinglufe/segment-anything-cpp-wrapper#42]
Hello, thank you for your efforts. Is it possible for you to support EdgeSam?

Thank you in advance!

**Comment by dinglufe** [comment]
Support for EdgeSAM has been added in [version 1.6](https://github.com/dinglufe/segment-anything-cpp-wrapper/releases/tag/v1.6).

**Comment by sctrueew** [comment]
Thanks
