### ISSUE TITLE
loadImage 

### ISSUE THREAD

**Issue by TPF0628** [dinglufe/segment-anything-cpp-wrapper#48]
When running the Run function in the loadImage function, it is always slow, is there any solution? Is the process a must every time a new picture is loaded? Can it be reused to reduce pre-treatment time?

**Comment by WilliManFR** [comment]
The only solution is to have a good gpu and run with cuda device. If you are running it on cpu, I'm not surprised. Image embedding is not real time (cf : paper of sam) !
