### ISSUE TITLE
automatic segmentation error

### ISSUE THREAD

**Issue by ygt7r21999** [dinglufe/segment-anything-cpp-wrapper#49]
It is a very nice code! I successfully run the points and box prompt code. However, there is some problem with the automatic segmentation. When I press "a" to run automatic segmentation in VS Studio2019, it returns an error window:
<img width="347" alt="0617-全分割时报错" src="https://github.com/dinglufe/segment-anything-cpp-wrapper/assets/63237337/76d73be4-acea-483f-8caa-321359cd8bde">

Can you help me with it?
btw, this is the program window to show some information for reference:
<img width="1485" alt="0617-ref窗口" src="https://github.com/dinglufe/segment-anything-cpp-wrapper/assets/63237337/475b4d05-cb26-4381-8594-8d6deb070b7c">

Thank you!

**Comment by dinglufe** [comment]
Have you used CrashDumps files to investigate where the error occurred, such as identifying the line of code?
