### ISSUE TITLE
Mask correctly detected but shifted when displayed

### ISSUE THREAD

**Issue by G2-Hamdi-Ben-Abdallah** [dinglufe/segment-anything-cpp-wrapper#51]
Hello,

Do you have an idea?
Thanks in advance

![Capture](https://github.com/dinglufe/segment-anything-cpp-wrapper/assets/125072933/82f9d53a-22da-40c8-b963-1f59c3d9c45c)

**Comment by G2-Hamdi-Ben-Abdallah** [comment]
This is due to the export of sam_model.onnx (bad version of segment_anything) installed.

**Comment by Svamei** [comment]
> This is due to the export of sam_model.onnx (bad version of segment_anything) installed.

I met the same problem, but I couldn't find the reason. Can you tell me more detailed reasons?
