### ISSUE TITLE
mask from box

### ISSUE THREAD

**Issue by bnascimento** [dinglufe/segment-anything-cpp-wrapper#6]
On the original demo, there is a method to turn a box into a mask. I think would be a nice addon here as well.

**Comment by dinglufe** [comment]
What kind of addon are you referring to? And does "original demo" mean [version 1.0](https://github.com/dinglufe/segment-anything-cpp-wrapper/releases/tag/v1.0)?

**Comment by bnascimento** [comment]
By original demo, I meant this: https://segment-anything.com/demo# 

Also from https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/notebooks/onnx_model_example.ipynb#L418
`point_labels: Labels for the sparse input prompts. 0 is a negative input point, 1 is a positive input point, 2 is a top-left box corner, 3 is a bottom-right box corner, and -1 is a padding point. If there is no box input, a single padding point with label -1 and coordinates (0.0, 0.0) should be concatenated.`
So a box where TL and BR points have 2 and 3 values.

What you understand here by padding?

**Comment by dinglufe** [comment]
Specifying the region is indeed a very important feature, I will add it.But I'm not sure what 'padding' means here.

**Comment by Jing-cai** [comment]
Hello, what will happen if I run on linux? Can I get through it?

**Comment by dinglufe** [comment]
> Hello, what will happen if I run on linux? Can I get through it?

I tested running the program on Linux before, but it crashed. However, it's possible that the machine I used for testing had insufficient memory (more test needed). We can continue the discussion on a new issue.

**Comment by bnascimento** [comment]
it can run yes

**Comment by dinglufe** [comment]
This feature (box prompt) was added in [v1.4](https://github.com/dinglufe/segment-anything-cpp-wrapper/releases/tag/v1.4).

> Specifying the region is indeed a very important feature, I will add it.But I'm not sure what 'padding' means here.

**Comment by Jing-cai** [comment]
> 



> > 你好，如果我在linux上运行会发生什么？我能熬过去吗？
> 
> 我之前在Linux上测试过运行该程序，但它崩溃了。但是，我用于测试的机器可能内存不足（需要更多测试）。我们可以继续讨论新的问题。

好的，看到博主又出提示框的方法，真的特激动，刚好是需要的，非常感谢

**Comment by Jing-cai** [comment]
> > > > 
> > > 
> > > 
> > > > > 你好，如果我在linux上运行会发生什么？我能熬过去吗？
> > > > 
> > > > 
> > > > 我之前在Linux上测试过运行该程序，但它崩溃了。但是，我用于测试的机器可能内存不足（需要更多测试）。我们可以继续讨论新的问题。
> > > 
> > > 
> > > 好的，看到博主又出提示框的方法，真的特激动，刚好是需要的，非常感谢
> > 
> > 
> > 不过我之前用python将进行推理将官网的代码改成了半精度推理，推理b模型显存值占了3.8g左右，其他两个都能在6g以内推理成功，那么我在想可以将模型转为半精度然后再转出onnx这样推理在c++这边会不会就会更加的快呢
> 
> 不过我试了下用官网的进行半精度导出onnx，没有成功，不知道是不行还是自己的方法没用对，博主要是有好的方法，可以一起讨论讨论
在新的cv::Mat mask = sam.getMask(points, nagativePoints, box);这个方法中，请问可以只输入box吗，其他两个可以不添加吗

**Comment by Jing-cai** [comment]
123

**Comment by Jacc999** [comment]
> > 
> 
> > > 你好，如果我在linux上运行会发生什么？我能熬过去吗？
> > 
> > 
> > 我之前在Linux上测试过运行该程序，但它崩溃了。但是，我用于测试的机器可能内存不足（需要更多测试）。我们可以继续讨论新的问题。
> 
> 好的，看到博主又出提示框的方法，刚好是需要的，非常感谢
