### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by qnmts** [dinglufe/segment-anything-cpp-wrapper#7]
![image](https://github.com/dinglufe/segment-anything-cpp-wrapper/assets/74292184/1d6f5282-3df5-436d-9600-dab7f7c93d40)

**Comment by dinglufe** [comment]
`#include <list>` should be added to `sam.h`, but I'm not sure why my compiler didn't produce any errors.

**Comment by qnmts** [comment]
> `#include <list>` should be added to `sam.h`, but I'm not sure why my compiler didn't produce any errors.

Thank you for your answer. The compilation was successful, but an error was reported during operation

 
![image](https://github.com/dinglufe/segment-anything-cpp-wrapper/assets/74292184/2b626e90-d87c-4aca-a46f-cd1073101d88)

**Comment by dinglufe** [comment]
Could it be missing DLL files? Try running the executable by double-clicking it or use [Dependency Walker](https://www.dependencywalker.com/) to check for dependencies.

**Comment by lixinye666** [comment]
同学你的cmake那个好用吗，你有没有遇到过这个问题CMake Error at build/vcpkg/scripts/buildsystems/vcpkg.cmake:855 (_find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:6 (find_package)
