### ISSUE TITLE
MobileSAM onnx model input type?

### ISSUE THREAD

**Issue by OroChippw** [dinglufe/segment-anything-cpp-wrapper#9]
Thank you for providing such good learning materials. I tried to use the export_pre_model.py file you provided to export the onnx model, and found that the input tensor format is uint8 instead of float32. Use the same method to convert the encoder on the official SAM model. , the input format of the obtained onnx model is float32, is this correct?
![image](https://github.com/dinglufe/segment-anything-cpp-wrapper/assets/75830178/f7e7df92-01e6-4ca5-a779-87044f08b63f)

**Comment by dinglufe** [comment]
There are two ONNX models: one for preprocessing (embedding) and one for inference. The preprocessing model takes input images of type uint8, while the inference model takes the float matrix obtained from preprocessing.

**Comment by OroChippw** [comment]
> There are two ONNX models: one for preprocessing (embedding) and one for inference. The preprocessing model takes input images of type uint8, while the inference model takes the float matrix obtained from preprocessing.

I get it~ I have decoupled the model while converting the input type to float32，But I found that the inference result of mobileSAM is not very well

**Comment by dinglufe** [comment]
> But I found that the inference result of mobileSAM is not very well

Yes, I have noticed that too. I initially thought it was a trade-off for lightweight implementation. However, it might be worth conducting a more detailed comparison using the official test data.
